---
id: rubykansai87-chat
base_name: actioncable-chat
tags:
- ruby
- rails
presentation_date: 2019/07/13
version: 2019.07.13.1
licenses: []
slideshare_id: action-cable-155279408
speaker_deck_id: action-cabledejian-yi-tiyatutowozuo-tutemita
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
